name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        git clone https://github.com/hybridgroup/gocv.git
        cd gocv
        make install
        cd ..
        echo "Successfully installed gocv!"
    
    - name: Granting private modules access
	    run: |
	      git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/corestario".insteadOf "https://github.com/corestario"

    - name: Build
      run: make build-linux

    - name: Test
      run: make test-short
